### ISSUE TITLE
Maru named wrongly

### ISSUE THREAD

**Issue by bentomama** [learn-co-curriculum/array-readme-qualifying#14]
In the array the cats names are: famous_cats = ["lil' bub", "grumpy cat", "Maru"]
But we are instructed to type in maru_cat = famous_cats.pop in order to remove the famous cat named Maru.
Given the array, wouldn't I type in maru = famous_cats.pop since the cat name in the array is Maru?

**Comment by AnnJohn** [comment]
hi @bentomama this looks like a question specific to you. Could you please use the Ask a Question tool and someone from our team will help you out and answer your question. Thanks!
