### ISSUE TITLE
should we mention that some of these methods do and others don't actually modify the array?

### ISSUE THREAD

**Issue by loganhasson** [learn-co-curriculum/array-readme-qualifying#7]

**Comment by PeterBell** [comment]
Hey @loganhasson is there any particular place where you'd like to see this added? As I look at this, it seems pretty clear to me that some operations modify the array (adding or removing elements using shovel, shift, etc) and some don't (like include?) so my first take is that it just might be more confusing to add a "list of methods that mutate arrays" or whatever. That said, if there's anything you'd like to change, feel free to submit a PR as a first cut.

Gonna close this out for now, but just reopen with comments and/or submit a PR if you'd like to go through this a little more!
